# Basic commands of Tensors

Tensor are used to storage multi-dimensional data, If you are familiar with Numpy we used by but associate as numpy.arrays. Tensor is fundamental in DP applications to represent input data as *arrays* for example to represent the color image as 3D tensor.

## Tensors in PyTorch

PyTorch has eith types: 3 float types (16, 32, 64 bit) and five integer types (8 signed, 8 unsigned, 16, 32, 64 bit). We have to represent them by different classes and the most common are **torch.FloatTensor** (being 32-bit), **torch.ByteTensor** (8-bit unsigned integer) and **torch.LongTensor** (64-bit signed integer).

Let us see some basic commands to call tensors:

In [3]:
import torch # PyTorch library
a = torch.FloatTensor(3, 2) # tensor with 3 rows and 2 columns
print(a)

tensor([[2.1858e-04, 1.1966e+22],
        [3.1097e-18, 6.4805e-10],
        [6.3007e-10, 4.2242e-05]])


PyTorch allocates memory for the tensor but it is empty.

We can clear the content with the following operation:

In [5]:
print(a.zero_())

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


**Pay attention**! PyTorch has two operations for tensors - *inplace* and *functional*. *Inplace* operation has an underscore, as below, to operate on the tensor's content. Coversely, the *Functional* operation creates a **copy** of the tensor with the operation, leaving the original tensor untouched. This example it would copy the tensor *a* with zero content.

In [7]:
# Initialize tensor with content
b = torch.FloatTensor([[1, 2, 3], [3, 2, 1]]) # As we are creating numpy.array
print(b)

tensor([[1., 2., 3.],
        [3., 2., 1.]])


Alternative example of creating the same tensor from numpy.array

In [10]:
# Other example
import numpy as np
c = np.zeros(shape=(3,2)) # size = 3x2
print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
d = torch.tensor(c) # Tensor form class FloatTensor(64-bit) with the content of c

In [17]:
# Example with different content
e = np.array([[1, 2, 3], [4, 5, 6]])
f = torch.tensor(e)
print(f)

tensor([[1, 2, 3],
        [4, 5, 6]])


## Operations with tensors

We have scalar tensors created in the same way as above (*a = torch.tensor(1)*) but they can also result from operations.

In [18]:
s = f.sum()
print(s)

tensor(21)


In [19]:
# How do we get the content of the tensor?
print(s.item())

21


**Voilá!!!**

In [20]:
# Operations with tensors
a + 1

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [26]:
# Other example
v_sum = b + e
print(v_sum) # element-wise sum
print(v_sum.sum()) # total sum

tensor([[2., 4., 6.],
        [7., 7., 7.]], dtype=torch.float64)
tensor(33., dtype=torch.float64)
